force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
                <default>true</default>
                <label>To Do</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Decline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Studio__c.field-meta.xml
<CustomField>
    <fullName>Studio__c</fullName>
    <label>Studio</label>
    <referenceTo>Studio__c</referenceTo>
    <relationshipLabel>Movies</relationshipLabel>
    <relationshipName>Movies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Studio__c/Studio__c.object-meta.xml
<CustomObject>
    <label>Studio</label>
    <nameField>
        <label>Studio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataFactory.cls
public class TestDataFactory{
    public static List<Movie__c> createMoviesList(Integer num, Id studioId, Boolean doInsert){
        List<Movie__c> moviesList = new List<Movie__c>();
        for (Integer i = 0; i < num; i++){
            moviesList.add(new Movie__c(Name = 'Test Movie' + i, Status__c = 'To Do', Studio__c = studioId));
        }
        if (doInsert){
            insert moviesList;
        }
        return moviesList;
    }

    public static List<Studio__c> createStudioList(Integer num, Boolean doInsert){
        List<Studio__c> studioList = new List<Studio__c>();
        for (Integer i = 0; i < num; i++){
            studioList.add(new Studio__c(Name = 'Test Studio' + i));
        }
        if (doInsert){
            insert studioList;
        }
        return studioList;
    }

    public static List<Employee__c> createEmployeeList(Integer num, Boolean doInsert){
        List<Employee__c> employeeList = new List<Employee__c>();
        for (Integer i = 0; i < num; i++){
            employeeList.add(new Employee__c(First_Name__c = 'Employee' + i, Last_Name__c = 'Test'));
        }
        if (doInsert){
            insert employeeList;
        }
        return employeeList;
    }

}