force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Studio__c.field-meta.xml
<CustomField>
    <fullName>Studio__c</fullName>
    <label>Studio</label>
    <referenceTo>Studio__c</referenceTo>
    <relationshipLabel>Movies</relationshipLabel>
    <relationshipName>Movies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Movie_Employee__c/Movie_Employee__c.object-meta.xml
<CustomObject>
    <label>Movie Employee</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Employee Movie Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movie Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie_Employee__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Employee_Movie_Relations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Movie_Employee__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipName>Employee_Movie_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Studio__c/Studio__c.object-meta.xml
<CustomObject>
    <label>Studio</label>
    <nameField>
        <label>Studio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MovieEmployeeTriggerTest.cls
@IsTest
public with sharing class MovieEmployeeTriggerTest{
    @TestSetup
    static void makeData(){
        List<Employee__c> employeeList = TestDataFactory.createEmployeeList(1, true);
        List<Studio__c> listStudio = TestDataFactory.createStudioList(1, true);
        List<Movie__c> movieList = TestDataFactory.createMoviesList(1, listStudio[0].Id, true);
    }

    @IsTest
    public static void preventDuplicatePositionOnEmployeeInsertTest(){
        List<Employee__c> employeeList = [SELECT Id
                                          FROM Employee__c
                                          LIMIT 1];
        List<Movie__c> movieList = [SELECT Id
                                    FROM Movie__c
                                    LIMIT 1];

        List<Movie_Employee__c> movieEmployeeList = new List<Movie_Employee__c>();

        for (Integer i = 0; i < 10; i++){
            movieEmployeeList.add(new Movie_Employee__c(Movie__c = movieList[0].Id, Employee__c = employeeList[0].Id, Position__c = 'TestPosition' + i));
            if (i < 5){
                movieEmployeeList.add(new Movie_Employee__c(Movie__c = movieList[0].Id, Employee__c = employeeList[0].Id, Position__c = 'TestPosition' + i));
            }
        }

        System.debug('movieEmployeeList: ' + movieEmployeeList);

        Test.startTest();
        Database.insert (movieEmployeeList, false);
        Test.stopTest();
        List<Movie_Employee__c> movieEmployeeResultList = [SELECT Id, Position__c
                                                           FROM Movie_Employee__c];
        System.debug('movieEmployeeResultList: ' + movieEmployeeResultList);

        System.debug('movieEmployeeResultList: ' + movieEmployeeResultList.size());
        System.assertEquals(10, movieEmployeeResultList.size());
    }

    @IsTest
    public static void preventDuplicatePositionOnEmployeeUpdateTest(){
    }

}