force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Represent a project information</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Worklog__c/Worklog__c.object-meta.xml
<CustomObject>
    <label>Worklog</label>
    <nameField>
        <displayFormat>W-{00000}</displayFormat>
        <label>Worklog Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Worklogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Worklog__c/fields/Actual_hours__c.field-meta.xml
<CustomField>
    <fullName>Actual_hours__c</fullName>
    <label>Actual hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Worklog__c/fields/Billable_hours__c.field-meta.xml
<CustomField>
    <fullName>Billable_hours__c</fullName>
    <inlineHelpText>Will be populated automatically if empty</inlineHelpText>
    <label>Billable hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Worklog__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the completed activity</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Worklog__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Worklogs</relationshipLabel>
    <relationshipName>Worklogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Worklog__c/fields/Sub_type__c.field-meta.xml
<CustomField>
    <fullName>Sub_type__c</fullName>
    <label>Sub-type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Call/Mailing</fullName>
            </value>
            <value>
                <fullName>Project Management</fullName>
            </value>
            <value>
                <fullName>Mentorship</fullName>
            </value>
            <value>
                <fullName>Study</fullName>
            </value>
            <value>
                <fullName>Internal event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Worklog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WorklogsListController.cls
public with sharing class WorklogsListController{
    public Id recordId{ get; set; }

    public Integer rowNumber{ get; set; }

    public Integer totalBillableHours{ get; set; }

    public Integer totalActualHours{ get; set; }

    public List<Worklog__c> worklogsList{ get; set; }

    public Project__c project{ get; set; }

    public Datetime dateCreation{ get; set; }

    public void getDateCreation(){
        this.dateCreation= Datetime.now();
    }

    public WorklogsListController(){
        this.recordId = ApexPages.currentPage().getParameters().get('id');
        this.rowNumber = -1;
        this.totalBillableHours = 0;
        this.totalActualHours = 0;

        this.project = [SELECT Id, Name, CreatedDate, Primary_Contact__c, Primary_Contact__r.Phone, Primary_Contact__r.Email
                        FROM Project__c
                        WHERE Id = :recordId];

        this.worklogsList = [SELECT Id, Description__c, Type__c, Sub_type__c, Actual_hours__c, Billable_hours__c
                             FROM Worklog__c
                             WHERE Project__c = :recordId];

        for (Worklog__C worklog_i : worklogsList){
            this.totalBillableHours += (Integer) worklog_i.Billable_hours__c;
            this.totalActualHours += (Integer) worklog_i.Actual_hours__c;
        }
        getDateCreation();
    }

}