force-app/main/default/objects/Cinema__c/Cinema__c.object-meta.xml
<CustomObject>
    <label>Cinema</label>
    <nameField>
        <label>Cinema Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cinemas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cinema__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country where the current cinema is located</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cinema_Movie__c/Cinema_Movie__c.object-meta.xml
<CustomObject>
    <label>Cinema Movie</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Cinema Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cinema Movies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cinema_Movie__c/fields/Cinema__c.field-meta.xml
<CustomField>
    <fullName>Cinema__c</fullName>
    <label>Cinema</label>
    <referenceTo>Cinema__c</referenceTo>
    <relationshipLabel>Cinema Movies</relationshipLabel>
    <relationshipName>Cinema_Movies</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cinema_Movie__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Cinema Movies</relationshipLabel>
    <relationshipName>Cinema_Movies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cinema_Movie__c/fields/Premiere_date__c.field-meta.xml
<CustomField>
    <fullName>Premiere_date__c</fullName>
    <label>Premiere date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cinema_Movie__c/fields/Shown_till__c.field-meta.xml
<CustomField>
    <fullName>Shown_till__c</fullName>
    <label>Shown till</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Country_Movie__c/Country_Movie__c.object-meta.xml
<CustomObject>
    <label>Country Movie</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Country Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country Movies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Movie__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Country Movies</relationshipLabel>
    <relationshipName>Country_Movies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Country_Movie__c/fields/Premiere_date__c.field-meta.xml
<CustomField>
    <fullName>Premiere_date__c</fullName>
    <description>premiere date of movie in the current country</description>
    <label>Premiere date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Country_Movie__c/fields/Shown_till__c.field-meta.xml
<CustomField>
    <fullName>Shown_till__c</fullName>
    <description>the last date where movie is shown in the cinema in the current country</description>
    <label>Shown till</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <formula>First_Name__c +&apos; &apos;+Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Studio__c.field-meta.xml
<CustomField>
    <fullName>Studio__c</fullName>
    <label>Studio</label>
    <referenceTo>Studio__c</referenceTo>
    <relationshipLabel>Movies</relationshipLabel>
    <relationshipName>Movies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Movie_Employee__c/Movie_Employee__c.object-meta.xml
<CustomObject>
    <label>Movie Employee</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Employee Movie Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movie Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie_Employee__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Employee_Movie_Relations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Movie_Employee__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipName>Employee_Movie_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Studio__c/Studio__c.object-meta.xml
<CustomObject>
    <label>Studio</label>
    <nameField>
        <label>Studio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CinemaScheduleController.cls
/**
 * Created by User on 17.03.2023.
 */
public with sharing class CinemaScheduleController{
    @AuraEnabled
    public static List<Movie_Employee__c> getCinemaMovies(Id cinemaRecordId, Date selectedDate){
        System.debug('cinemaRecordId: ' + cinemaRecordId);
        System.debug('selectedDate: ' + selectedDate);

        String country;

        //1 Get cinema record info
        Cinema__c cinemaRecord = [SELECT Id, Country__c
                                  FROM Cinema__c
                                  WHERE Id = :cinemaRecordId];
        country = cinemaRecord.Country__c;

        //Get information about all movies related to the cinema according to date that user selected
        List<Cinema_Movie__c> cinemaMovieList = [SELECT Id, Premiere_date__c, Shown_till__c, Movie__c, Movie__r.Name, Cinema__r.Country__c
                                                 FROM Cinema_Movie__c
                                                 WHERE Cinema__c = :cinemaRecordId AND Shown_till__c >= :selectedDate AND Premiere_date__c <= :selectedDate];
        System.debug('cinemaMovieList: ' + cinemaMovieList);

        // List where we will put all movies that still shown
        List<Id> movieResultIdsList = new List<Id>();

        if (!cinemaMovieList.isEmpty()){
            for (Cinema_Movie__c cinemaMovie_i : cinemaMovieList){
                movieResultIdsList.add(cinemaMovie_i.Movie__c);
            }
        }

        //Get all movies from Country Movie tab except movies that we already have in the Cinema Movie tab
        List<Country_Movie__c> countryMovieList = [SELECT Id, Country__c, Shown_till__c, Premiere_date__c, Movie__c, Movie__r.Name
                                                   FROM Country_Movie__c
                                                   WHERE Country__c = :country AND Movie__c NOT IN:movieResultIdsList AND Shown_till__c >= :selectedDate AND Premiere_date__c <= :selectedDate];
        System.debug('countryMovieList: ' + countryMovieList);

        if (!countryMovieList.isEmpty()){
            for (Country_Movie__c countryMovie_i : countryMovieList){
                movieResultIdsList.add(countryMovie_i.Movie__c);
            }
        }

        List<Movie_Employee__c> movieEmployeesList = [SELECT Employee__r.Employee_Name__c, Position__c, Movie__c, Movie__r.Name, Movie__r.Studio__r.Name
                                                      FROM Movie_Employee__c
                                                      WHERE Position__c = 'Director' AND Movie__c IN:movieResultIdsList];

        
            System.debug('Returning List ' + movieEmployeesList);
            return movieEmployeesList;
       
    }
}