force-app/main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <label>Issue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Issue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectIssuesController.cls
public with sharing class ProjectIssuesController{
    @AuraEnabled
    public static List<Issue__c> obtainIssues(Id projectId){
        System.debug('projectId: ' + projectId);
        try{

            return [SELECT Id, Assignee__c,Summary__c
                    FROM Issue__c
                    WHERE Id =:projectId];


        } catch (Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
}