force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Denie_To_Delete__c.field-meta.xml
<CustomField>
    <fullName>Denie_To_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Denie To Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
                <default>true</default>
                <label>To Do</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Decline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie_setting_rule__mdt/Movie_setting_rule__mdt.object-meta.xml
<CustomObject>
    <label>Movie setting rule</label>
    <pluralLabel>Movie setting rules</pluralLabel>
</CustomObject>

force-app/main/default/objects/Movie_setting_rule__mdt/fields/StatusFrom__c.field-meta.xml
<CustomField>
    <fullName>StatusFrom__c</fullName>
    <label>StatusFrom</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
                <default>true</default>
                <label>To Do</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Decline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie_setting_rule__mdt/fields/StatusTo__c.field-meta.xml
<CustomField>
    <fullName>StatusTo__c</fullName>
    <label>StatusTo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
                <default>true</default>
                <label>To Do</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Decline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MovieReleaseDateSetValue__c/MovieReleaseDateSetValue__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Movie Release Date Set Value</label>
</CustomObject>

force-app/main/default/objects/MovieReleaseDateSetValue__c/fields/ReleaseDateSetWord__c.field-meta.xml
<CustomField>
    <fullName>ReleaseDateSetWord__c</fullName>
    <label>ReleaseDateSetWord</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MovieTriggerHandler.cls
/**
 * Created by User on 02.03.2023.
 */
public with sharing class MovieTriggerHandler extends TriggerHandler{
    public override void beforeInsert(){
    }

    public override void beforeUpdate(){
        checkStatusField((Map<Id, Movie__c>)Trigger.oldMap, Trigger.new );
    }

    public override void beforeDelete(){
        checkPickField((Map<Id, Movie__c>)Trigger.oldMap);
    }

    public override void afterInsert(){
    }

    public override void afterUpdate(){
    }

    public override void afterDelete(){
    }

    public override void afterUndelete(){
    }

    private static void checkStatusField(Map<Id, Movie__c> oldMoviesMap, List<Movie__c> newMoviesList){

        List<Movie_setting_rule__mdt> metadataList = Movie_setting_rule__mdt.getAll().values();

        MovieReleaseDateSetValue__c releaseDateSetWord = MovieReleaseDateSetValue__c.getOrgDefaults();

        Map<String, Set<String>> metadataMap = new Map<String, Set<String>>();

        for (Movie_setting_rule__mdt metadata_i : metadataList){
            if (metadataMap.containsKey(metadata_i.StatusFrom__c)){
                metadataMap.get(metadata_i.StatusFrom__c).add(metadata_i.StatusTo__c);
            } else{
                metadataMap.put(metadata_i.StatusFrom__c, new Set<String>{ metadata_i.StatusTo__c });
            }
        }
        String releaseDateSetterStatus = releaseDateSetWord.ReleaseDateSetWord__c;

        for (Movie__c movie_i : newMoviesList){
            Boolean validStatusValues = false;

            if (Trigger.isUpdate){
                if (!oldMoviesMap.get(movie_i.Id).Status__c.equals(movie_i.Status__c)){

                    if (metadataMap.containsKey(oldMoviesMap.get(movie_i.Id).Status__c) && metadataMap.get(oldMoviesMap.get(movie_i.Id).Status__c).contains(movie_i.Status__c)){
                        validStatusValues = true;
                    }
                    if (!validStatusValues){
                        movie_i.addError('You cannot switch from ' + oldMoviesMap.get(movie_i.Id).Status__c + ' to ' + movie_i.Status__c);
                    }
                    if (movie_i.Status__c.equals(releaseDateSetterStatus)){
                        System.debug('Release date set');
                        movie_i.Release_date__c = Date.today();
                    }
                }
            }
        }
    }

    private static void checkPickField(Map<Id, Movie__c> oldMoviesMap){
        for (Id movieId_i : oldMoviesMap.keySet()){
            if (oldMoviesMap.get(movieId_i).Denie_To_Delete__c == true){
                oldMoviesMap.get(movieId_i).addError('You cannot delete this movie because it is denied to delete.');
            }
        }
    }

}