force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
                <default>true</default>
                <label>To Do</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Decline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeleteMoviesBatch.cls
global class DeleteMoviesBatch implements Schedulable, Database.Batchable<SObject>, Database.Stateful{
    global String errorsLog = '';
    public void execute(SchedulableContext context){
        Database.executeBatch(this);
    }

    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('SELECT Id FROM Movie__c WHERE Status__c=\'Decline\'');
    }

    public void execute(Database.BatchableContext BC, List<Movie__c> moviesList){

        Database.DeleteResult[] deleteResults = Database.delete (moviesList, false);
        for (Database.DeleteResult deleteResult : deleteResults){
            if (deleteResult.isSuccess()){
                System.debug('Record deleted successfully!');
            } else{
                System.debug('Record delete failed!');
            }
            for (Database.Error err : deleteResult.getErrors()){
                errorsLog += 'Record Id: ' + deleteResult.getId() + ' | Message: ' + err.getMessage() + '\n';
            }
        }
        System.debug('errorsLog in execute: ' + errorsLog);
    }

    public void finish(Database.BatchableContext BC){
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems
                            FROM AsyncApexJob
                            WHERE Id = :bc.getJobId()];

        // Send an email notification
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(new List<String>{ 'sergeybaklanov468@gmail.com' });
        mail.setSubject('Batch Apex Job ' + job.Status);
        String body = 'The Batch Apex Job ' + job.Id + ' completed with Status: ' + job.Status + '.';
        body += 'Processed ' + job.JobItemsProcessed + ' of ' + job.TotalJobItems + ' jobs.';
        body += 'Number of errors: ' + job.NumberOfErrors + '.\n';

        body += errorsLog;
        System.debug('errorsLog in finish: ' + errorsLog);

        mail.setPlainTextBody(body);
        Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ mail });
        System.debug('Email sended: ' + body);
    }

}