force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
                <default>true</default>
                <label>To Do</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Decline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Studio__c.field-meta.xml
<CustomField>
    <fullName>Studio__c</fullName>
    <label>Studio</label>
    <referenceTo>Studio__c</referenceTo>
    <relationshipLabel>Movies</relationshipLabel>
    <relationshipName>Movies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Studio__c/Studio__c.object-meta.xml
<CustomObject>
    <label>Studio</label>
    <nameField>
        <label>Studio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DeleteMoviesBatchTest.cls
@IsTest
private with sharing class DeleteMoviesBatchTest{
    @TestSetup
    static void makeData(){
        List<Studio__c> studioList = TestDataFactory.createStudioList(1, true);
        List<Movie__c> movieList = TestDataFactory.createMoviesList(10, studioList[0].Id, true);

        List<Movie__c> moviesToUpdateList = new List<Movie__c>();

        for (Movie__c movie_i : [SELECT Id, Status__c
                                 FROM Movie__c
                                 WHERE Status__c = 'To Do'
                                 LIMIT 5]){

            movie_i.Status__c = 'Decline';

            moviesToUpdateList.add(movie_i);
        }
        update moviesToUpdateList;
    }

    @IsTest
    static void deleteMoviesTest(){
        Test.startTest();
        DeleteMoviesBatch testedBatch = new DeleteMoviesBatch();
        testedBatch.execute(null);
        Test.stopTest();

        List<Movie__c> moviesResultList = [SELECT Id
                                           FROM Movie__c
                                           WHERE Status__c = 'Decline'];
        System.debug('moviesResultList: ' + moviesResultList);

        System.assertNotEquals(null, [SELECT Id
                                      FROM Movie__c
                                      WHERE Status__c = 'Decline'].size(), 'Records with Decline wasn\'t deleted');
    }

}